---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.201.149.89
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/libexec/platform-python

vector:
  hosts:
    vector-01:
      ansible_host: 84.201.149.89
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/id_rsa