---
  - src: https://github.com/lauragrechenko/ansible-clickhouse
    scm: git
    version: "1.0.0"
    name: clickhouse
  - src: https://github.com/lauragrechenko/lighthouse-role
    scm: git
    version: "1.0.0"
    name: lighthouse
  - src: https://github.com/lauragrechenko/vector-role
    scm: git
    version: "1.0.0"
    name: vector