apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app-chart.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
      protocol: TCP
