{
 "title": "Mon-02-task-2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\",mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "утилизация CPU для nodeexporter (в процентах, 100-idle);",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{cpu-utilization}}"
    }
   ]
  }
 ]
}