---
all:
  hosts:
    nexus-01:
      ansible_host: 158.160.185.246
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_yc
    ansible_python_interpreter: /usr/libexec/platform-python
