{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.appName }}
  namespace: {{ include "pandora-box.namespace" . }}
  labels:
    {{- include "pandora-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.app }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backupsName }}
  namespace: {{ include "pandora-box.namespace" . }}
  labels:
    {{- include "pandora-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.backups }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end -}}
