#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx_base
- name: Install Nginx (RedHat family)
  ansible.builtin.dnf:
    name: "{{ nginx_package_name }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Enable SELinux httpd_can_network_connect when SELinux is enforcing
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: Deploy temporary welcome page
  ansible.builtin.copy:
    content: "<h1>Nginx is running</h1>"
    dest: /usr/share/nginx/html/index.html
    mode: '0644'