---
vector_version: "0.36.0"
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
vector_install_dir: "/opt/vector"
vector_config_dir: "/etc/vector"
vector_archive_path: "/tmp/vector.tar.gz"
vector_template_local_path: "templates/vector.toml.j2"